#!/bin/bash
# This is an update version of the script found at 
# http://forum.xda-developers.com/wiki/index.php?title=Extract_initramfs_from_zImage
#
# The problem with that script is that the gzip magic number occasionally occur 
# naturally, meaning that some non-compressed files get uncompressed.

reset

DEBUG=1




zImage=$1
compression_type=$2

case $2 in
    bzip2)
        compress='\x{5D}\x{00}\x..\x{FF}\x{FF}\x{FF}\x{FF}\x{FF}\x{ FF}';;

    gzip)
        compress='\x1F\x8B\x08';;

    lzma)
        compress='\x{5D}\x{00}\x..\x{FF}\x{FF}\x{FF}\x{FF}\x{FF}\x{FF}';;

    *) compress='\x1F\x8B\x08';;
esac


#========================================================
# find start of gziped kernel object in the zImage file:
#========================================================
pos=`grep -P -a -b -m 1 --only-matching '\x1F\x8B\x08' $zImage | cut -f 1 -d :`
echo "-I- Extracting gzip'd kernel image from \"$zImage\" (start = $pos)"

if [ ! $pos = "" ]; then
    dd if=$zImage of=/tmp/kernel.gz bs=1 skip=$pos 2>/dev/null >/dev/null
    gunzip -qf /tmp/kernel.gz
    inputfile=kernel
else
    echo "-E- $2'd kernel image not found"; exit 1
fi


#==========================================================================
# find start and end of the "cpio" initramfs image inside the kernel object:
# ASCII cpio header starts with '070701'
# The end of the cpio archive is marked with an empty file named TRAILER!!!
#==========================================================================
start="`grep -a -b -m 1 --only-matching '070701' /tmp/${inputfile} | head -1 | cut -f 1 -d :`"
end="`grep -a -b -m 1 --only-matching 'TRAILER!!!' /tmp/${inputfile} | head -1 | cut -f 1 -d :`"


[ -z $DEBUG ] || echo "-I- Kernel start = $start"
[ -z $DEBUG ] || echo "-I- Kernel end = $end"

if [ -z $start ] || [ -z $end ]; then
   #========================================================================
   # No cpio archive found, assuming compressed
   #========================================================================
   echo "-I- Extracting compressed cpio image from kernel image (start = $pos)"
   pos=`grep -P -a -b -m 1 --only-matching "${compress}" /tmp/${inputfile} | cut -f 1 -d :`

   [ -z $DEBUG ] || echo "dd if=/tmp/${inputfile} bs=1 skip=$pos | gunzip -q > /tmp/cpio.img"
   dd if=/tmp/${inputfile} bs=1 skip=$pos | gunzip -q > /tmp/cpio.img
   inputfile=cpio.img

   start=`grep -a -b -m 1 --only-matching '070701' /tmp/${inputfile} | head -1 | cut -f 1 -d :`
   end=`grep -a -b -m 1 --only-matching 'TRAILER!!!' /tmp/${inputfile} | head -1 | cut -f 1 -d :`

else
    echo "-I- Already uncompressed cpio.img, not decompressing"

fi   

end=$((end + 10))
count=$((end - start))
if (($count < 0)); then
    echo "-E- Couldn't match start/end of the initramfs image."
    exit
fi

echo "-I- Extracting initramfs image from $inputfile (start = $start, end = $end)"
dd if=/tmp/$inputfile bs=1 skip=$start count=$count > initramfs.cpio
